"""miniplan zuteilung einstellungen

Revision ID: 05f5b4ba628d
Revises: fb23ac9c6d2d
Create Date: 2026-07-12 10:57:15.327993

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "05f5b4ba628d"
down_revision: str | None = "fb23ac9c6d2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "miniplaene",
        sa.Column("fairness_gewicht", sa.Float(), server_default="1.0", nullable=False),
    )
    op.add_column(
        "miniplaene",
        sa.Column("mindestabstand_tage", sa.Integer(), server_default="6", nullable=False),
    )
    op.add_column(
        "miniplaene", sa.Column("mixing_gewicht", sa.Float(), server_default="0.0", nullable=False)
    )
    op.add_column(
        "miniplaene",
        sa.Column("wiederholung_gewicht", sa.Float(), server_default="0.0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("miniplaene", "wiederholung_gewicht")
    op.drop_column("miniplaene", "mixing_gewicht")
    op.drop_column("miniplaene", "mindestabstand_tage")
    op.drop_column("miniplaene", "fairness_gewicht")
    # ### end Alembic commands ###
