"""gruppen mindestanzahl pro dienst typ

Revision ID: 27a105adf0f7
Revises: 3d63a122b3bc
Create Date: 2026-07-04 19:00:52.217551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27a105adf0f7'
down_revision: Union[str, None] = '3d63a122b3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dienst_typ_gruppen_anforderungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dienst_typ_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('mindest_anzahl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dienst_typ_id'], ['dienst_typen.id'], ),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dienst_typ_id', 'gruppe_id', name='uq_dienst_typ_gruppen_anforderung')
    )
    op.execute(
        "INSERT INTO dienst_typ_gruppen_anforderungen (dienst_typ_id, gruppe_id, mindest_anzahl) "
        "SELECT dienst_typ_id, gruppe_id, 0 FROM dienst_typ_gruppen"
    )
    op.drop_table('dienst_typ_gruppen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dienst_typ_gruppen',
    sa.Column('dienst_typ_id', sa.INTEGER(), nullable=False),
    sa.Column('gruppe_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dienst_typ_id'], ['dienst_typen.id'], ),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppen.id'], ),
    sa.PrimaryKeyConstraint('dienst_typ_id', 'gruppe_id')
    )
    op.execute(
        "INSERT INTO dienst_typ_gruppen (dienst_typ_id, gruppe_id) "
        "SELECT dienst_typ_id, gruppe_id FROM dienst_typ_gruppen_anforderungen"
    )
    op.drop_table('dienst_typ_gruppen_anforderungen')
    # ### end Alembic commands ###
