"""Stammdaten: Gruppen, Minis, Dienst-Typen

Revision ID: 3d63a122b3bc
Revises: 3f14e737a81e
Create Date: 2026-07-04 13:14:57.131792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d63a122b3bc'
down_revision: Union[str, None] = '3f14e737a81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dienst_typen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfarrei_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard_anzahl', sa.Integer(), nullable=False),
    sa.Column('erforderliche_filtertags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pfarrei_id'], ['pfarreien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pfarrei_id', 'name', name='uq_dienst_typ_pfarrei_name')
    )
    op.create_table('gruppen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfarrei_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pfarrei_id'], ['pfarreien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pfarrei_id', 'name', name='uq_gruppe_pfarrei_name')
    )
    op.create_table('dienst_typ_gruppen',
    sa.Column('dienst_typ_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dienst_typ_id'], ['dienst_typen.id'], ),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppen.id'], ),
    sa.PrimaryKeyConstraint('dienst_typ_id', 'gruppe_id')
    )
    op.create_table('minis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfarrei_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filtertags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppen.id'], ),
    sa.ForeignKeyConstraint(['pfarrei_id'], ['pfarreien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minis')
    op.drop_table('dienst_typ_gruppen')
    op.drop_table('gruppen')
    op.drop_table('dienst_typen')
    # ### end Alembic commands ###
