"""Indizes fuer Ferienzeitraum- und FiltertagBlocker-Lookups

Revision ID: 3d7ea724e31e
Revises: b01bc2026715
Create Date: 2026-07-14 19:03:09.926468

"""

from collections.abc import Sequence

from alembic import op

revision: str = "3d7ea724e31e"
down_revision: str | None = "b01bc2026715"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_ferienzeitraeume_pfarrei_zeitraum",
        "ferienzeitraeume",
        ["pfarrei_id", "start_datum", "end_datum"],
        unique=False,
    )
    op.create_index(
        "ix_filtertag_blocker_lookup",
        "filtertag_blocker",
        ["pfarrei_id", "filtertag_id", "wochentag"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_filtertag_blocker_lookup", table_name="filtertag_blocker")
    op.drop_index("ix_ferienzeitraeume_pfarrei_zeitraum", table_name="ferienzeitraeume")
    # ### end Alembic commands ###
