"""initial schema

Revision ID: 3f14e737a81e
Revises: 
Create Date: 2026-07-04 11:51:55.180416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f14e737a81e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ist_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutzer_email'), 'nutzer', ['email'], unique=True)
    op.create_table('pfarreien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nutzer_pfarrei_rollen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('pfarrei_id', sa.Integer(), nullable=False),
    sa.Column('rolle', sa.Enum('PFARREI_VERANTWORTLICHER', 'BETRACHTER', name='pfarreirolle'), nullable=False),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.ForeignKeyConstraint(['pfarrei_id'], ['pfarreien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nutzer_id', 'pfarrei_id', name='uq_nutzer_pfarrei')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutzer_pfarrei_rollen')
    op.drop_table('pfarreien')
    op.drop_index(op.f('ix_nutzer_email'), table_name='nutzer')
    op.drop_table('nutzer')
    # ### end Alembic commands ###
