"""ferienzeiten und bundesland

Revision ID: 6ed9239f2f5d
Revises: 905b8fdfdd3c
Create Date: 2026-07-04 19:15:50.853537

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6ed9239f2f5d"
down_revision: str | None = "905b8fdfdd3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ferienzeitraeume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pfarrei_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_datum", sa.Date(), nullable=False),
        sa.Column("end_datum", sa.Date(), nullable=False),
        sa.Column("schuljahr", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["pfarrei_id"],
            ["pfarreien.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "pfarreien",
        sa.Column(
            "bundesland",
            sa.Enum(
                "BW",
                "BY",
                "BE",
                "BB",
                "HB",
                "HH",
                "HE",
                "MV",
                "NI",
                "NW",
                "RP",
                "SL",
                "SN",
                "ST",
                "SH",
                "TH",
                name="bundesland",
            ),
            nullable=False,
            server_default="BY",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfarreien", "bundesland")
    op.drop_table("ferienzeitraeume")
    # ### end Alembic commands ###
