"""miniplan gottesdienst dienstbedarf editor

Revision ID: 6f7471145215
Revises: c7ce7adb7115
Create Date: 2026-07-04 20:23:39.350391

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6f7471145215"
down_revision: str | None = "c7ce7adb7115"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "miniplaene",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pfarrei_id", sa.Integer(), nullable=False),
        sa.Column("monat", sa.Integer(), nullable=False),
        sa.Column("jahr", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_BEARBEITUNG", "ABGESCHLOSSEN", name="miniplanstatus"),
            nullable=False,
        ),
        sa.Column("veranstaltungen", sa.Text(), nullable=True),
        sa.Column("ankuendigungen", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pfarrei_id"],
            ["pfarreien.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pfarrei_id", "monat", "jahr", name="uq_miniplan_pfarrei_monat_jahr"),
    )
    op.create_table(
        "gottesdienste",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("miniplan_id", sa.Integer(), nullable=False),
        sa.Column("datum", sa.Date(), nullable=False),
        sa.Column("uhrzeit", sa.Time(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["miniplan_id"],
            ["miniplaene.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dienstbedarf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gottesdienst_id", sa.Integer(), nullable=False),
        sa.Column("dienst_typ_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("anzahl", sa.Integer(), nullable=False),
        sa.Column("erforderliche_filtertags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dienst_typ_id"],
            ["dienst_typen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gottesdienst_id"],
            ["gottesdienste.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dienstbedarf_gruppen_anforderungen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dienstbedarf_id", sa.Integer(), nullable=False),
        sa.Column("gruppe_id", sa.Integer(), nullable=False),
        sa.Column("mindest_anzahl", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dienstbedarf_id"],
            ["dienstbedarf.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gruppe_id"],
            ["gruppen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dienstbedarf_id", "gruppe_id", name="uq_dienstbedarf_gruppen_anforderung"
        ),
    )
    op.create_table(
        "dienstbedarf_zuweisungen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dienstbedarf_id", sa.Integer(), nullable=False),
        sa.Column("mini_id", sa.Integer(), nullable=False),
        sa.Column("manuell_fixiert", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dienstbedarf_id"],
            ["dienstbedarf.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mini_id"],
            ["minis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dienstbedarf_id", "mini_id", name="uq_dienstbedarf_zuweisung"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dienstbedarf_zuweisungen")
    op.drop_table("dienstbedarf_gruppen_anforderungen")
    op.drop_table("dienstbedarf")
    op.drop_table("gottesdienste")
    op.drop_table("miniplaene")
    # ### end Alembic commands ###
