"""login versuche fuer rate limit

Revision ID: 79f9de967fe3
Revises: a868d4469175
Create Date: 2026-07-16 23:40:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "79f9de967fe3"
down_revision: str | None = "a868d4469175"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_versuche",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(length=64), nullable=False),
        sa.Column("versucht_um", sa.Float(), nullable=False),
        # Unterscheidet die Aktion, gegen die das Rate-Limit greift (z.B. "login",
        # "einladung_annehmen") - ein Client soll durch viele Login-Versuche nicht auch das
        # Annehmen von Einladungen (oder umgekehrt) blockieren, obwohl beide sich denselben
        # Zähler-Mechanismus teilen (siehe app/rate_limit.py).
        sa.Column("aktion", sa.String(length=32), nullable=False, server_default="login"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_versuche_aktion_client_ip_versucht_um",
        "login_versuche",
        ["aktion", "client_ip", "versucht_um"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_login_versuche_aktion_client_ip_versucht_um", table_name="login_versuche")
    op.drop_table("login_versuche")
    # ### end Alembic commands ###
