"""filtertag blocker

Revision ID: 905b8fdfdd3c
Revises: 27a105adf0f7
Create Date: 2026-07-04 19:10:04.167817

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "905b8fdfdd3c"
down_revision: str | None = "27a105adf0f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filtertag_blocker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pfarrei_id", sa.Integer(), nullable=False),
        sa.Column(
            "filtertag",
            sa.Enum("GRUNDSCHUELER", "SCHUELER", "ARBEITER", name="filtertag"),
            nullable=False,
        ),
        sa.Column("wochentag", sa.Integer(), nullable=False),
        sa.Column("start_zeit", sa.Time(), nullable=False),
        sa.Column("end_zeit", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pfarrei_id"],
            ["pfarreien.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filtertag_blocker")
    # ### end Alembic commands ###
