"""mini miniplan limit und ignoriere flags

Revision ID: a868d4469175
Revises: ef819a33987c
Create Date: 2026-07-16 22:55:33.056563

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a868d4469175"
down_revision: str | None = "ef819a33987c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mini_miniplan_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("miniplan_id", sa.Integer(), nullable=False),
        sa.Column("mini_id", sa.Integer(), nullable=False),
        sa.Column("max_einsaetze", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["mini_id"], ["minis.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["miniplan_id"], ["miniplaene.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("miniplan_id", "mini_id", name="uq_mini_miniplan_limit"),
    )
    op.add_column(
        "miniplaene",
        sa.Column("ignoriere_max_einsaetze", sa.Boolean(), server_default="0", nullable=False),
    )
    op.add_column(
        "miniplaene",
        sa.Column(
            "ignoriere_gruppen_mindestanzahl", sa.Boolean(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "miniplaene",
        sa.Column("ignoriere_verfuegbarkeit", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("miniplaene", "ignoriere_verfuegbarkeit")
    op.drop_column("miniplaene", "ignoriere_gruppen_mindestanzahl")
    op.drop_column("miniplaene", "ignoriere_max_einsaetze")
    op.drop_table("mini_miniplan_limits")
    # ### end Alembic commands ###
