"""dienst_typ erforderliche_filtertags entfernen

Revision ID: bf1df9e7930a
Revises: c3b3ace1b1f5
Create Date: 2026-07-07 00:03:15.767809

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

revision: str = "bf1df9e7930a"
down_revision: str | None = "c3b3ace1b1f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dienst_typen", "erforderliche_filtertags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dienst_typen", sa.Column("erforderliche_filtertags", sqlite.JSON(), nullable=False)
    )
    # ### end Alembic commands ###
