"""dienst typ zeige label und gottesdienst notiz

Revision ID: c3b3ace1b1f5
Revises: 5c13f29a84b9
Create Date: 2026-07-04 23:07:37.084605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3b3ace1b1f5'
down_revision: Union[str, None] = '5c13f29a84b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default nötig, damit ALTER TABLE ... ADD COLUMN NOT NULL auf bestehenden Zeilen
    # funktioniert (SQLite verlangt hierfür einen Default); entspricht den Python-seitigen
    # `default`-Werten der Modelle.
    op.add_column(
        'dienst_typen',
        sa.Column('zeige_label', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'dienstbedarf',
        sa.Column('zeige_label', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column('gottesdienste', sa.Column('notiz', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gottesdienste', 'notiz')
    op.drop_column('dienstbedarf', 'zeige_label')
    op.drop_column('dienst_typen', 'zeige_label')
    # ### end Alembic commands ###
