"""feiertag einstellungen

Revision ID: c7ce7adb7115
Revises: 6ed9239f2f5d
Create Date: 2026-07-04 19:26:12.543939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7ce7adb7115'
down_revision: Union[str, None] = '6ed9239f2f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feiertag_einstellungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfarrei_id', sa.Integer(), nullable=False),
    sa.Column('feiertag_key', sa.String(length=64), nullable=False),
    sa.Column('schulfrei', sa.Boolean(), nullable=False),
    sa.Column('arbeiter_frei', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pfarrei_id'], ['pfarreien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pfarrei_id', 'feiertag_key', name='uq_feiertag_einstellung_pfarrei_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feiertag_einstellungen')
    # ### end Alembic commands ###
