"""mini und miniplan max einsaetze

Revision ID: ef819a33987c
Revises: 3d7ea724e31e
Create Date: 2026-07-16 17:13:14.546212

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ef819a33987c"
down_revision: str | None = "3d7ea724e31e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("miniplaene", sa.Column("max_einsaetze_standard", sa.Integer(), nullable=True))
    op.add_column("minis", sa.Column("max_einsaetze_pro_monat", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("minis", "max_einsaetze_pro_monat")
    op.drop_column("miniplaene", "max_einsaetze_standard")
    # ### end Alembic commands ###
