"""pfarrei bild

Revision ID: f520a2df503d
Revises: 05f5b4ba628d
Create Date: 2026-07-12 11:01:30.785894

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f520a2df503d"
down_revision: str | None = "05f5b4ba628d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pfarreien", sa.Column("bild_dateiname", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfarreien", "bild_dateiname")
    # ### end Alembic commands ###
